const sharp = require('sharp');

/**
 * Convert an image file to G-code for the Horus 3 Pro plotter.
 *
 * Supported styles:
 *   - "halftone"  : varying-size circles, density based on darkness
 *   - "hatching"  : parallel lines with variable spacing
 *   - "stipple"   : random dots with density based on darkness
 *   - "spiral"    : continuous spiral with radius modulated by brightness
 */
async function convertImageToGcode(imagePath, opts = {}) {
  const {
    style = 'hatching',
    width = 200,         // plot width in mm
    penDown = 5,         // Z position pen down
    penUp = 0,           // Z position pen up
    speed = 3000,        // feed rate mm/min
    spacing = 3,         // line/dot spacing in mm
  } = opts;

  // Load and preprocess image
  const meta = await sharp(imagePath).metadata();
  const aspect = meta.height / meta.width;
  const plotHeight = width * aspect;

  // Resize to a manageable pixel grid (1 pixel ≈ spacing mm)
  const gridCols = Math.round(width / spacing);
  const gridRows = Math.round(plotHeight / spacing);

  const { data, info } = await sharp(imagePath)
    .resize(gridCols, gridRows, { fit: 'fill' })
    .grayscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  // Build brightness grid (0 = black, 1 = white)
  const grid = [];
  for (let y = 0; y < gridRows; y++) {
    const row = [];
    for (let x = 0; x < gridCols; x++) {
      const idx = (y * info.width + x);
      const brightness = data[idx] / 255;
      row.push(brightness);
    }
    grid.push(row);
  }

  let gcode;
  let preview;

  switch (style) {
    case 'halftone':
      ({ gcode, preview } = halftone(grid, { width, plotHeight, spacing, penDown, penUp, speed }));
      break;
    case 'hatching':
      ({ gcode, preview } = hatching(grid, { width, plotHeight, spacing, penDown, penUp, speed }));
      break;
    case 'stipple':
      ({ gcode, preview } = stipple(grid, { width, plotHeight, spacing, penDown, penUp, speed }));
      break;
    case 'spiral':
      ({ gcode, preview } = spiral(grid, { width, plotHeight, spacing, penDown, penUp, speed }));
      break;
    default:
      ({ gcode, preview } = hatching(grid, { width, plotHeight, spacing, penDown, penUp, speed }));
  }

  return { gcode, preview };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function header(penUp) {
  return [
    '; Generated by Horus Plotter App',
    'G21 ; mm',
    'G90 ; absolute coords',
    `G0 Z${penUp} ; pen up`,
    'G0 X0 Y0 ; home',
    '',
  ].join('\n');
}

function footer(penUp) {
  return [
    '',
    `G0 Z${penUp} ; pen up`,
    'G0 X0 Y0 ; return home',
    'M2 ; end',
  ].join('\n');
}

function penDownCmd(z, speed) {
  return `G1 Z${z} F${speed}`;
}

function penUpCmd(z, speed) {
  return `G0 Z${z}`;
}

function moveTo(x, y, speed) {
  return `G0 X${x.toFixed(2)} Y${y.toFixed(2)}`;
}

function lineTo(x, y, speed) {
  return `G1 X${x.toFixed(2)} Y${y.toFixed(2)} F${speed}`;
}

// ─── Halftone ───────────────────────────────────────────────────────────────
// Draw circles of varying radius. Darker = bigger circle.

function halftone(grid, opts) {
  const { width, plotHeight, spacing, penDown, penUp, speed } = opts;
  const rows = grid.length;
  const cols = grid[0].length;
  const maxRadius = spacing * 0.45;
  const preview = [];

  const lines = [header(penUp)];

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const darkness = 1 - grid[r][c]; // 0=white, 1=black
      if (darkness < 0.1) continue; // skip white areas

      const radius = darkness * maxRadius;
      if (radius < 0.3) continue;

      const cx = c * spacing;
      const cy = (rows - 1 - r) * spacing; // flip Y

      // Draw circle as small polygon (8 segments)
      const segments = 8;
      lines.push(moveTo(cx + radius, cy, speed));
      lines.push(penDownCmd(penDown, speed));

      preview.push({ type: 'circle', cx, cy, r: radius });

      for (let i = 1; i <= segments; i++) {
        const angle = (2 * Math.PI * i) / segments;
        const px = cx + radius * Math.cos(angle);
        const py = cy + radius * Math.sin(angle);
        lines.push(lineTo(px, py, speed));
      }
      lines.push(penUpCmd(penUp, speed));
    }
  }

  lines.push(footer(penUp));
  return { gcode: lines.join('\n'), preview };
}

// ─── Hatching ───────────────────────────────────────────────────────────────
// Parallel lines with variable spacing based on darkness.

function hatching(grid, opts) {
  const { width, plotHeight, spacing, penDown, penUp, speed } = opts;
  const rows = grid.length;
  const cols = grid[0].length;
  const preview = [];

  const lines = [header(penUp)];
  const lineSpacing = spacing;

  // Horizontal passes
  for (let r = 0; r < rows; r++) {
    const y = (rows - 1 - r) * lineSpacing;
    let drawing = false;
    let segStart = 0;

    for (let c = 0; c <= cols; c++) {
      const darkness = c < cols ? (1 - grid[r][c]) : 0;
      const shouldDraw = darkness > 0.15;

      if (shouldDraw && !drawing) {
        // Start drawing
        const x = c * lineSpacing;
        lines.push(moveTo(x, y, speed));
        lines.push(penDownCmd(penDown, speed));
        segStart = c;
        drawing = true;
      } else if (!shouldDraw && drawing) {
        // Stop drawing
        const x = c * lineSpacing;
        lines.push(lineTo(x, y, speed));
        lines.push(penUpCmd(penUp, speed));
        preview.push({ type: 'line', x1: segStart * lineSpacing, y1: y, x2: x, y2: y });
        drawing = false;
      }
    }
    if (drawing) {
      const x = cols * lineSpacing;
      lines.push(lineTo(x, y, speed));
      lines.push(penUpCmd(penUp, speed));
      preview.push({ type: 'line', x1: segStart * lineSpacing, y1: y, x2: x, y2: y });
    }
  }

  // Diagonal cross-hatching for darker areas (45° lines)
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const darkness = 1 - grid[r][c];
      if (darkness < 0.5) continue; // only add cross-hatch for darker areas

      const x = c * lineSpacing;
      const y = (rows - 1 - r) * lineSpacing;
      const len = lineSpacing * 0.7;

      lines.push(moveTo(x - len / 2, y - len / 2, speed));
      lines.push(penDownCmd(penDown, speed));
      lines.push(lineTo(x + len / 2, y + len / 2, speed));
      lines.push(penUpCmd(penUp, speed));
      preview.push({ type: 'line', x1: x - len / 2, y1: y - len / 2, x2: x + len / 2, y2: y + len / 2 });
    }
  }

  lines.push(footer(penUp));
  return { gcode: lines.join('\n'), preview };
}

// ─── Stipple ────────────────────────────────────────────────────────────────
// Random dots with density based on darkness.

function stipple(grid, opts) {
  const { width, plotHeight, spacing, penDown, penUp, speed } = opts;
  const rows = grid.length;
  const cols = grid[0].length;
  const preview = [];

  const lines = [header(penUp)];
  const dotSize = 0.5; // mm

  // Seeded random for reproducibility
  let seed = 42;
  function rand() {
    seed = (seed * 16807 + 0) % 2147483647;
    return seed / 2147483647;
  }

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const darkness = 1 - grid[r][c];
      if (darkness < 0.1) continue;

      // Number of dots proportional to darkness
      const numDots = Math.floor(darkness * 4);

      for (let d = 0; d < numDots; d++) {
        const cx = c * spacing + rand() * spacing;
        const cy = (rows - 1 - r) * spacing + rand() * spacing;

        lines.push(moveTo(cx, cy, speed));
        lines.push(penDownCmd(penDown, speed));
        lines.push(lineTo(cx + dotSize, cy, speed));
        lines.push(penUpCmd(penUp, speed));
        preview.push({ type: 'dot', cx, cy });
      }
    }
  }

  lines.push(footer(penUp));
  return { gcode: lines.join('\n'), preview };
}

// ─── Spiral ─────────────────────────────────────────────────────────────────
// Continuous spiral from center outward, radius modulated by brightness.

function spiral(grid, opts) {
  const { width, plotHeight, spacing, penDown, penUp, speed } = opts;
  const rows = grid.length;
  const cols = grid[0].length;
  const preview = [];

  const lines = [header(penUp)];
  const centerX = width / 2;
  const centerY = plotHeight / 2;
  const maxRadius = Math.min(width, plotHeight) / 2;
  const turns = maxRadius / spacing;
  const totalSteps = Math.round(turns * 360);
  const angleStep = (2 * Math.PI * turns) / totalSteps;

  let firstMove = true;

  for (let i = 0; i < totalSteps; i++) {
    const angle = i * angleStep;
    const baseRadius = (i / totalSteps) * maxRadius;

    // Sample brightness at this point
    const px = centerX + baseRadius * Math.cos(angle);
    const py = centerY + baseRadius * Math.sin(angle);

    const col = Math.floor(px / spacing);
    const row = rows - 1 - Math.floor(py / spacing);

    let darkness = 0.3;
    if (row >= 0 && row < rows && col >= 0 && col < cols) {
      darkness = 1 - grid[row][col];
    }

    // Modulate radius by darkness
    const modRadius = baseRadius + darkness * spacing * 0.3;
    const x = centerX + modRadius * Math.cos(angle);
    const y = centerY + modRadius * Math.sin(angle);

    if (darkness > 0.1) {
      if (firstMove) {
        lines.push(moveTo(x, y, speed));
        lines.push(penDownCmd(penDown, speed));
        firstMove = false;
      } else {
        lines.push(lineTo(x, y, speed));
      }
      preview.push({ type: 'point', x, y });
    } else {
      if (!firstMove) {
        lines.push(penUpCmd(penUp, speed));
        firstMove = true;
      }
    }
  }

  if (!firstMove) {
    lines.push(penUpCmd(penUp, speed));
  }

  lines.push(footer(penUp));
  return { gcode: lines.join('\n'), preview };
}

module.exports = { convertImageToGcode };
